In [2]:
import numpy as np

Work with the NUmpy arrays with of One DImension


In [3]:
oneDarrauy = np.array([1,2,3,4,5,6])
print(oneDarrauy)
print("the number of dimensions in the array is: ", oneDarrauy.ndim)


[1 2 3 4 5 6]
the number of dimensions in the array is:  1


Arrays with two DIme dimension

In [4]:
twoDarrays =  np.array([[1,2,3,4],
                        [2,3,4,5]])
print(twoDarrays)
print("the number of dimensions in the array is: ",twoDarrays.ndim)

[[1 2 3 4]
 [2 3 4 5]]
the number of dimensions in the array is:  2


Work whit tree Dimension Arrays 

In [7]:
ThreeDarrays = np.array([
[[1,2,3],[4,5,6]],
[[-2,-3,-4],[12,32,34]]
])
print(ThreeDarrays)
print("the number of dimensions in the array is: ", ThreeDarrays[0][1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[-2 -3 -4]
  [12 32 34]]]
the number of dimensions in the array is:  4
