In [7]:
import numpy as np

In [8]:
TreeDarray = np.array([
    [
        [1,2,3,4],[5,5,6,7]
        ],
    [
        [1,2,3,4],[5,5,6,7]
    ]
])


In [9]:
for i in TreeDarray:
    for j in i:
        print (j)

[1 2 3 4]
[5 5 6 7]
[1 2 3 4]
[5 5 6 7]


In [6]:
for i in TreeDarray:
    for j in i:
        for k in j:
            print (k)

1
2
3
4
5
5
6
7
1
2
3
4
5
5
6
7
